window.SITE_CONFIG = {
  whatsapp: "5524999334587",
  whatsappMessagePrefix: "Olá! Vi este item no catálogo e gostaria de saber mais"
};

/*
  COMO EDITAR:
  - name: nome do produto
  - category: categoria ou linha
  - presentation: caixa, unidade, ampola etc.
  - specification: detalhe complementar
  - price: preço principal
  - image: caminho da imagem dentro de assets/products/
*/

window.PRODUCTS = [
  {
    name: "T.G. ampola 15mg",
    category: "Seleção Sheila",
    presentation: "Caixa com 1 unidade",
    specification: "15mg",
    price: "R$ 350,00",
    oldPrice: "",
    installment: "R$ 400,00 no pix ou cartão de crédito 18x",
    rating: "4,9",
    reviews: "128 avaliações",
    badge: "MAIS ESCOLHIDO",
    availability: "Disponível",
    description: "T.G. ampola 15mg",
    image: "assets/products/produto-01.png",
    accent: "green"
  },
  {
    name: "T.G. caixa com 4 ampolas 15mg",
    category: "Seleção Sheila",
    presentation: "Caixa com 4 unidades",
    specification: "15mg",
    price: "R$ 1.200,00",
    oldPrice: "",
    installment: "R$ 1.300,00 no pix ou cartão de crédito 18x",
    rating: "4,8",
    reviews: "94 avaliações",
    badge: "SELEÇÃO",
    availability: "Disponível",
    description: "caixa com 4 ampolas 15mg",
    image: "assets/products/produto-02.png",
    accent: "green"
  },
  {
    name: "LIPOLAND ampola 15mg",
    category: "Seleção Sheila",
    presentation: "Ampola avulsa",
    specification: "15mg",
    price: "R$ 450,00",
    oldPrice: "",
    installment: "R$ 500,00 no pix ou cartão de crédito 18x",
    rating: "5,0",
    reviews: "76 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "LIPOLAND ampola 15mg",
    image: "assets/products/produto-03.png",
    accent: "green"
  },
  {
    name: "LIPOLAND caixa com 4 ampolas 15mg",
    category: "Seleção Sheila",
    presentation: "Caixa com 4 ampolas",
    specification: "15mg",
    price: "R$ 1.300,00",
    oldPrice: "",
    installment: "R$ 1.400,00 no pix ou cartão de crédito 18x",
    rating: "4,9",
    reviews: "151 avaliações",
    badge: "DESTAQUE",
    availability: "Disponível",
    description: "caixa com 4 ampolas 15mg",
    image: "assets/products/produto-04.png",
    accent: "green"
  },
  {
    name: "LIPOLESS ampola 15mg",
    category: "Seleção Sheila",
    presentation: "Ampola avulsa",
    specification: "15mg",
    price: "R$ 450,00",
    oldPrice: "",
    installment: "R$ 500,00 no pix ou cartão de crédito 18x",
    rating: "4,9",
    reviews: "87 avaliações",
    badge: "SELEÇÃO",
    availability: "Disponível",
    description: "ampola 15mg",
    image: "assets/products/produto-05.png",
    accent: "green"
  },
  {
    name: "LIPOLESS caixa com 4 ampolas 15mg",
    category: "Seleção Sheila",
    presentation: "4 ampolas",
    specification: "15mg",
    price: "R$ 1.300,00",
    oldPrice: "",
    installment: "R$ 1400,00 no pix ou cartão de crédito 18x",
    rating: "4,8",
    reviews: "69 avaliações",
    badge: "DESTAQUE",
    availability: "Disponível",
    description: "caixa com 4 ampolas 15mg.",
    image: "assets/products/produto-06.png",
    accent: "green"
  },
  {
    name: "TIZERC ampola 15mg",
    category: "Seleção Sheila",
    presentation: "Ampola avulsa",
    specification: "15mg",
    price: "R$ 450,00",
    oldPrice: "",
    installment: "R$ 500,00 no pix ou cartão de crédito 18x",
    rating: "5,0",
    reviews: "112 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "ampola 15mg.",
    image: "assets/products/produto-07.png",
    accent: "green"
  },
  {
    name: "TIZERC caixa com 4 ampolas 15mg",
    category: "Seleção Sheila",
    presentation: "4 ampolas",
    specification: "15mg",
    price: "R$ 1.350,00",
    oldPrice: "",
    installment: "R$ 1.450,00 no pix ou cartão de crédito 18x",
    rating: "4,9",
    reviews: "103 avaliações",
    badge: "SELEÇÃO",
    availability: "Disponível",
    description: "caixa com 4 ampolas 15mg.",
    image: "assets/products/produto-08.png",
    accent: "green"
  },
  {
    name: "TG ampola 15mg",
    category: "Seleção Sheila",
    presentation: "Ampola avulsa",
    specification: "15mg",
    price: "R$ 350,00",
    oldPrice: "",
    installment: "R$ 400,00 no pix ou cartão de crédito 18x",
    rating: "4,8",
    reviews: "81 avaliações",
    badge: "DESTAQUE",
    availability: "Disponível",
    description: "ampola 15mg.",
    image: "assets/products/produto-09.png",
    accent: "green"
  },
  {
    name: "TG caixa com 4 ampolas 15mg",
    category: "Seleção Sheila",
    presentation: "4 ampolas",
    specification: "15mg",
    price: "R$ 1.200,00",
    oldPrice: "",
    installment: "R$ 1.300,00 no pix ou cartão de crédito 18x",
    rating: "5,0",
    reviews: "140 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "caixa com 4 ampolas 15mg.",
    image: "assets/products/produto-10.png",
    accent: "green"
  },
  {
    name: "VELTRANE caixa fechada 90mg",
    category: "Seleção Sheila",
    presentation: "",
    specification: "90mg",
    price: "R$ 1,350,00",
    oldPrice: "",
    installment: "no pix ou cartão de crédito 18x",
    rating: "5,0",
    reviews: "140 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "caixa fechada 90mg.",
    image: "assets/products/produto-11.png",
    accent: "green"
  },
  {
    name: "RETRATUTIDE caneta 40mg",
    category: "Seleção Sheila",
    presentation: "Caneta",
    specification: "40mg",
    price: "R$ 15.990,00",
    oldPrice: "",
    installment: "no pix ou cartão de crédito 18x",
    rating: "5,0",
    reviews: "140 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "Caneta 40mg.",
    image: "assets/products/produto-12.png",
    accent: "green"
  },
  {
    name: "SERINGA 100mg",
    category: "Seleção Sheila",
    presentation: "Seringa",
    specification: "100mg",
    price: "R$ 4,00",
    oldPrice: "",
    installment: "",
    rating: "5,0",
    reviews: "140 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "Seringa 100mg.",
    image: "assets/products/produto-13.png",
    accent: "green"
  }
  ];
