window.PRODUCTS = [
  {
    name: "Produto 01",
    category: "Linha Premium",
    presentation: "Caixa com 1 unidade",
    specification: "Apresentação individual",
    price: "R$ 0.000,00",
    oldPrice: "R$ 0.000,00",
    installment: "12x de R$ 000,00 sem juros",
    rating: "4,9",
    reviews: "128 avaliações",
    badge: "MAIS ESCOLHIDO",
    availability: "Disponível",
    description: "Adicione aqui uma descrição curta com a apresentação, quantidade e principal informação do produto.",
    image: "assets/products/produto-01.png",
    accent: "blue"
  },
  {
    name: "Produto 02",
    category: "Linha Premium",
    presentation: "Caixa com 4 unidades",
    specification: "Apresentação com quatro unidades",
    price: "R$ 0.000,00",
    oldPrice: "R$ 0.000,00",
    installment: "12x de R$ 000,00 sem juros",
    rating: "4,8",
    reviews: "94 avaliações",
    badge: "SELEÇÃO",
    availability: "Disponível",
    description: "Use este espaço para explicar de forma clara o que acompanha a apresentação.",
    image: "assets/products/produto-02.png",
    accent: "violet"
  },
  {
    name: "Produto 03",
    category: "Edição Especial",
    presentation: "Ampola avulsa",
    specification: "1 ampola",
    price: "R$ 0.000,00",
    oldPrice: "R$ 0.000,00",
    installment: "12x de R$ 000,00 sem juros",
    rating: "5,0",
    reviews: "76 avaliações",
    badge: "EXCLUSIVO",
    availability: "Disponível",
    description: "Insira aqui as especificações essenciais sem deixar o cartão visualmente carregado.",
    image: "assets/products/produto-03.png",
    accent: "gold"
  },
  {
    name: "Produto 04",
    category: "Linha Selecionada",
    presentation: "Unidade",
    specification: "Embalagem individual",
    price: "R$ 0.000,00",
    oldPrice: "R$ 0.000,00",
    installment: "12x de R$ 000,00 sem juros",
    rating: "4,9",
    reviews: "151 avaliações",
    badge: "DESTAQUE",
    availability: "Disponível",
    description: "Descrição curta, objetiva e fácil de comparar com os demais produtos.",
    image: "assets/products/produto-04.png",
    accent: "cyan"
  },
  {
    name: "Produto 05",
    category: "Linha Premium",
    presentation: "Caixa com 1 unidade",
    specification: "Apresentação individual",
    price: "R$ 0.000,00",
    oldPrice: "R$ 0.000,00",
    installment: "12x de R$ 000,00 sem juros",
    rating: "4,7",
    reviews: "62 avaliações",
    badge: "NOVIDADE",
    availability: "Disponível",
    description: "Você pode adicionar ou remover produtos apenas copiando ou apagando este bloco.",
    image: "assets/products/produto-05.png",
    accent: "rose"
  },
  {
    name: "Produto 06",
    category: "Linha Premium",
    presentation: "Caixa com 4 unidades",
    specification: "Apresentação com quatro unidades",
    price: "R$ 0.000,00",
    oldPrice: "R$ 0.000,00",
    installment: "12x de R$ 000,00 sem juros",
    rating: "4,9",
    reviews: "109 avaliações",
    badge: "PREMIUM",
    availability: "Disponível",
    description: "Mantenha as imagens com fundo transparente para preservar o efeito premium.",
    image: "assets/products/produto-06.png",
    accent: "emerald"
  }
];
